### ISSUE TITLE
Clear instructions to run this program

### ISSUE THREAD

**Issue by codesuman** [VarunS2002/Python-NSE-Option-Chain-Analyzer#10]
Looks like a promising project but am unable to find proper instructions to run the same on my local. Could you please help me out on this.

**Comment by VarunS2002** [comment]
@codesuman  Usage instructions: https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/blob/master/README.md#Usage

**Comment by codesuman** [comment]
@VarunS2002 this is after starting the application. But how do i start the application was my question ?

**Comment by VarunS2002** [comment]
@codesuman Download the exe file and run it🤷🏻‍♂️

**Comment by codesuman** [comment]
Pardon my lack of Python knowledge. I see there is a dependency **auto-py-to-exe**, i assume it should create an exe file. But am unable to do the same on my local after running the command - `python3 NSE_Option_Chain_Analyzer.py`. Needed help on this line.

**Comment by VarunS2002** [comment]
@codesuman 
If you're using Windows just download the exe directly and run it : https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/releases/download/5.0/NSE_Option_Chain_Analyzer_5.0.exe
If you're running Linux, this program doesn't support Linux.

**Comment by codesuman** [comment]
My bad, i never looked into that Release section. Thanks !
