### ISSUE TITLE
SSL Wrong Version Number

### ISSUE THREAD

**Issue by MahadevanAnandhan** [VarunS2002/Python-NSE-Option-Chain-Analyzer#12]
am getting below error after start the .py file

requests.exceptions.SSLError: HTTPSConnectionPool(host='www.nseindia.com', port=443): Max retries exceeded with url: /products-services/equity-derivatives-list-underlyings-information (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))

**Comment by VarunS2002** [comment]
@MahadevanAnandhan Have you tried running it today? Or the .exe file?

**Comment by MahadevanAnandhan** [comment]
> @MahadevanAnandhan Have you tried running it today? Or the .exe file?

Tried today, py file and exe, getting the same error for both

 It is working without proxy. not working through the proxy.

**Comment by VarunS2002** [comment]
@MahadevanAnandhan Then it is not a problem in this program, the website probably doesn't allow proxy connections
