### ISSUE TITLE
NSE Data time difference 

### ISSUE THREAD

**Issue by Sangram2905** [VarunS2002/Python-NSE-Option-Chain-Analyzer#13]
Hello Varun,

This is not an issue but an request, if you may observed the  general time difference of NSE site data is 2.5 min but some time its more than 7 to 8 ....or some time it just stops....

Like Today at 11:07 AM the BankNifty pull the data last 10:56AM follow the image System time and Data Time column 
![image](https://user-images.githubusercontent.com/59437406/108462784-3a670d80-72a3-11eb-8a8d-d311593057f2.png)
 
In my program I modified the pop up to show time difference more than 7 min...
![image](https://user-images.githubusercontent.com/59437406/108462914-726e5080-72a3-11eb-8163-b948ac932633.png)

![image](https://user-images.githubusercontent.com/59437406/108465560-43a6a900-72a8-11eb-9cc2-b13dcab3dfd8.png)

if you like this idea you can also incorporate it.

Also an friendly advice   Do not use NSE name or Logo in program.

"""
os_time = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') 
os_update_time = datetime.datetime.strptime(os_time, '%Y-%m-%d %H:%M:%S')
                
opc_time = current_time
opc_time_update = datetime.datetime.strptime(opc_time, '%d-%b-%Y %H:%M:%S')

diff_time = os_update_time - opc_time_update
self.minutes = diff_time.total_seconds() / 60
#print(self.minutes)
if self.first_run:
   print("First Run")
elif self.minutes >= 7:
   messagebox.showinfo(title="Time difference", message="Time difference is more than 7 min")

"""

Keep the good work, Cheers.

Regards,
Sangram

**Comment by VarunS2002** [comment]
@Sangram2905 Sorry for replying late. I'm really busy with work lately. I'll get back to this later👍🏻

**Comment by Sangram2905** [comment]
No Issues Bro, may be some IDE req. to "import datetime , time" 

Keep the good work.

Regards,
Sangram

**Comment by ranjeetkesri** [comment]
make this in the chart. the difference should be shown in the chart for a better understanding

**Comment by VarunS2002** [comment]
@ranjeetkesri Which chart?

**Comment by ranjeetkesri** [comment]
the difference should be shown in a chart using matplotlib, I am using excel VBA don't know python coding

**Comment by ranjeetkesri** [comment]
can i contact you on your email for discussion ??

**Comment by VarunS2002** [comment]
@ranjeetkesri Sorry man I'm really busy with work these days so new features are currently not my priority. Also I'm personally not a trader so if you have any strategy or related questions I'm afraid I can't answer.

**Comment by ranjeetkesri** [comment]
I have my own system in excel, which working fine for me very accurately, want the same in python... but don't know python coding

**Comment by Sangram2905** [comment]
@ranjeetkesri  Hi, Sorry to contact you here but your contact details are missing, if you req. any help on python program 
plz drop me an Email with your contact details on sangram.phadke07@gmail.com.
I will contact you.

**Comment by dhairyatapadia** [comment]
@ranjeetkesri

 I am facing issue with Excel VBA code.  Could you please provide me your Excel VBA code on mail Dhairya.tapadia@gmail.com. 
 What am trying to do finding out sudden spike/change in OI in Call/Put which identify change direction of index/stock

Sorry Author for using your space for discussion.

**Comment by VarunS2002** [comment]
@Sangram2905 Do you have your own version of this program?

**Comment by Sangram2905** [comment]
Hello @VarunS2002,

Yes, I use your program as base for visualization but the internal core "calculation logic" is completely change
and its base on  logic https://www.youtube.com/watch?v=qfyLd-mu7gU&ab_channel=LearnStockMarketTrading

The program base on your older version program around Nov.2020

Also added the my own logic for ML & Graphs and so on...
The file can be found in https://github.com/Sangram2905/NSE_Option_Chain  

if any issues plz msg me, Keep the good work.
Regards,
Sangram

**Comment by VarunS2002** [comment]
@Sangram2905 That's very impressive.
I'll take a look at it soon.
Keep up the good work too✌🏻

**Comment by VarunS2002** [comment]
@Sangram2905 Time Difference feature added in commit : https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/commit/1bf1bb658992eff86dd29a5fce3aad6d3baa9bd5
Will be added in the next stable release

**Comment by Sangram2905** [comment]
Thanks Varun, This is the best Visual Option chain analysis I ever seen.

Also it's very easy to modify.

Keep the Good work.

Closing this issue.
