### ISSUE TITLE
Interview

### ISSUE THREAD

**Issue by Sangram2905** [VarunS2002/Python-NSE-Option-Chain-Analyzer#14]
Hi Varun,

We were impressed by your NSE OC Analyzer code and would like to invite you to interview for our upcoming YouTube channel dedicated to Stock Market programmer.
If you are interested please send us an Email on "sangram.phadke07@gmail.com" with your contact details.

Sorry to creating issue, as no contact details found.

Regards,
Sangram

**Comment by VarunS2002** [comment]
@Sangram2905 Thanks man, I appreciate the offer, but I'm not an investor. I'm actually an IT guy who made this software for my client. If you want to use/teach this program on your channel go ahead. Do post the channel link here, and best of luck!

**Comment by Sangram2905** [comment]
Ok as you wish, keep the good work.
