### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by johnbest5673** [VarunS2002/Python-NSE-Option-Chain-Analyzer#16]
Hi Varun, 

First of all Thanks for this wonderful tool as it is helping me to fetch the Option Chain from NSE. 
As I am not a student of Mr. Dharaskar, the only advantage for me is to retrieve the Chain, every 
"n" minutes. I would like to have an additional feature, if possible. Humble request.

An additional column in csv with the Spot Price of the underlying will be of more help. 

Regards

**Comment by VarunS2002** [comment]
@johnbest5673 
If the only advantage for you is to retrieve the Chain, every
"n" minutes, you can use the `Dump Entire Option Chain to CSV` feature.
This retrieves the NSE data and puts it in the csv file without any changes.
So you can run your own preferred calculations using Excel or Python, etc

**Comment by johnbest5673** [comment]
Hi Varun,

Thanks for the reply.

I am already doing this, but I need corresponding SPOT Value at that time. :)
If you could add this to the dumped file, will be helpful. 

Regards

**Comment by johnbest5673** [comment]
Hi Varun,

I am attaching an image. 
An extra column (red colored) at the end, is what I am asking for. 

Also adding a timestamp would be an added advantage, if you could... 👍 

Enough from me. :)


![python](https://user-images.githubusercontent.com/5575342/114873766-4392d780-9e19-11eb-9f9e-503af9fbe07a.PNG)

**Comment by VarunS2002** [comment]
@johnbest5673 
This feature won't be implemented, that file is for unmodified data.
You can retrieve the price from the other csv file by using `Live Exporting to CSV` feature.
Re-open this if there is anything else.
Thanks!
