### ISSUE TITLE
Is this suppported in mac?

### ISSUE THREAD

**Issue by shivkumr-code** [VarunS2002/Python-NSE-Option-Chain-Analyzer#18]
I am trying to install this in mac/linux. The installation commands are very vague. I installed the requirements.txt and also downloaded the .py file. what is the next step? where can I find?

Also, is there any way where I can run this in command line mode, if GUI is not yet implemented for Mac

**Comment by VarunS2002** [comment]
@shivkumr-code It is officially not supported on mac but it might be possible to run it. 
Do you know Python?

**Comment by shivkumr-code** [comment]
Yeah, I tried running it, it runs without any issues.

**Comment by VarunS2002** [comment]
@shivkumr-code Are all features working properly?

**Comment by VarunS2002** [comment]
@shivkumr-code  If everything is working perfectly then I need your help to add proper instructions for Mac in README. You in?

**Comment by shivkumr-code** [comment]
Yes, I am in. it works in Mac with python3. Have not tried all the features
yet. But the data is updating in real time. I just started learning
options. So I am not sure what important features to check.

**Comment by VarunS2002** [comment]
@shivkumr-code Can you share the exact steps and commands required to run this on Mac?
Installing tkinter/ all modules
