### ISSUE TITLE
Incorrect strike price

### ISSUE THREAD

**Issue by dipankar-npowered** [VarunS2002/Python-NSE-Option-Chain-Analyzer#23]
When I am trying to put strike price 18000, It is saying Incorrect "Strike Price. Please enter correct Strike Price."

**Comment by damodarnaidugali** [comment]
same issue with me

**Comment by VarunS2002** [comment]
@dipankar-npowered @damodarnaidugali  
The NSE website was itself not working till now so the app wasn't working. Try using it now.

**Comment by dipankar-npowered** [comment]
> @dipankar-npowered @damodarnaidugali The NSE website was itself not working till now so the app wasn't working. Try using it now.

Yeah it's working.
