### ISSUE TITLE
Does it have Macbook support app?

### ISSUE THREAD

**Issue by dipankar-npowered** [VarunS2002/Python-NSE-Option-Chain-Analyzer#24]
Does it have a Macbook support app? I was trying to build it on my MacBook but getting the following error.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/dipankar/opt/anaconda3/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/Users/dipankar/opt/anaconda3/lib/python3.8/tkinter/__init__.py", line 804, in callit
    func(*args)
  File "NSE_Option_Chain_Analyzer.py", line 1571, in main
    self.set_values()
  File "NSE_Option_Chain_Analyzer.py", line 1397, in set_values
    self.sheet.see(last_row)
  File "/Users/dipankar/Projects/Option-Chain-Analysis/env/lib/python3.8/site-packages/tksheet/_tksheet.py", line 1169, in see
    self.MT.see(row, column, keep_yscroll, keep_xscroll, bottom_right_corner, check_cell_visibility = check_cell_visibility, redraw = redraw)
  File "/Users/dipankar/Projects/Option-Chain-Analysis/env/lib/python3.8/site-packages/tksheet/_tksheet_main_table.py", line 1164, in see
    yvis, xvis = self.cell_is_completely_visible(r = r, c = c, separate_axes = True)
  File "/Users/dipankar/Projects/Option-Chain-Analysis/env/lib/python3.8/site-packages/tksheet/_tksheet_main_table.py", line 1220, in cell_is_completely_visible
    x1, y1, x2, y2 = self.GetCellCoords(r = r, c = c, sel = True)
  File "/Users/dipankar/Projects/Option-Chain-Analysis/env/lib/python3.8/site-packages/tksheet/_tksheet_main_table.py", line 2610, in GetCellCoords
    return self.col_positions[c] + 1,self.row_positions[r] + 1, self.col_positions[c + 1], self.row_positions[r + 1]
IndexError: list index out of range
```
And display is looking like:
![Screenshot 2021-10-02 at 11 29 04 AM](https://user-images.githubusercontent.com/66316261/135705467-3efe1515-0a4c-4eb3-bc85-561b436610bc.png)

**Comment by VarunS2002** [comment]
@dipankar-npowered 
Since I don't have one, I'm unable to test it. 
However this error seems to be in the tksheet library and not my program, not completely sure though.

**Comment by VarunS2002** [comment]
@dipankar-npowered 
Possibly fixed the issue in fd0981cf846c08628bb69d1f450a76ecb6df570e
Downgrade (or upgrade) to version 5.0.24 of tksheet using `pip install tksheet==5.0.24` and get back

**Comment by VarunS2002** [comment]
@dipankar-npowered Do all the available features work as expected on a Mac?

**Comment by dipankar-npowered** [comment]
> @dipankar-npowered Do all the available features work as expected on a Mac?

Yes, it's working as of now.

**Comment by VarunS2002** [comment]
@dipankar-npowered 
Could you later help me complete the documentation for MacOS like the one [here](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer#method-2-windows-and-linux)

**Comment by dipankar-npowered** [comment]
I tried to build the app for mac os for you.
Here is the link [https://drive.google.com/drive/folders/1XGSEs7ljyE9GniabZ8uLuxDsxNIJW16V?usp=sharing](url)
Some color issues are there. You can check it.

**Comment by dipankar-npowered** [comment]
> https://drive.google.com/drive/folders/1XGSEs7ljyE9GniabZ8uLuxDsxNIJW16V?usp=sharing

It's in debug mode. You can open by 
`open -a NSE_Option_Chain_Analyzer.app`

**Comment by VarunS2002** [comment]
@dipankar-npowered 
That's pretty cool but I don't have a Mac to try it. Correct me if I'm wrong, since python can be installed and programs can be run without building on Mac, I was hoping I'll add instructions for how to do that for users in documentation just like I did for Linux

**Comment by dipankar-npowered** [comment]
> @dipankar-npowered That's pretty cool but I don't have a Mac to try it. Correct me if I'm wrong, since python can be installed and programs can be run without building on Mac, I was hoping I'll add instructions for how to do that for users in documentation just like I did for Linux

Yes @VarunS2002 All steps are the same in mac to run this codebase as Linux.
Nothing to change.

**Comment by VarunS2002** [comment]
@dipankar-npowered 
- Requirements:
    - Python 3.6+
    - Additional steps for Linux:
        - `apt-get install python3-tk`
        - `apt install python3-pip`
    - For Windows https://www.python.org/downloads/ is recommended

- Download the `.py` (Python Source Code) file

- Required
  modules: [requirements.txt](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/blob/master/requirements.txt)

- Install missing modules using `pip install -r requirements.txt`


## Even these commands are exactly the same?

**Comment by VarunS2002** [comment]
> I tried to build the app for mac os for you. Here is the link [https://drive.google.com/drive/folders/1XGSEs7ljyE9GniabZ8uLuxDsxNIJW16V?usp=sharing](url) Some color issues are there. You can check it.

Are these color issues present if you run it directly instead  of building?

**Comment by dipankar-npowered** [comment]
* Requirements:
   
   * Python 3.6+
   * Additional steps for Linux:
     
     * `apt-get install python3-tk`
     * `apt install python3-pip`
   * Additional steps for Mac OS:
     
     * `brew install python3`
     * `brew install python-tk`
   * For Windows https://www.python.org/downloads/ is recommended
 * Download the `.py` (Python Source Code) file
 * Required
   modules: [requirements.txt](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/blob/master/requirements.txt)
 * Install missing modules using `pip install -r requirements.txt`
 * `python NSE_Option_Chain_Analyzer.py`

**Comment by dipankar-npowered** [comment]
> > I tried to build the app for mac os for you. Here is the link [https://drive.google.com/drive/folders/1XGSEs7ljyE9GniabZ8uLuxDsxNIJW16V?usp=sharing](url) Some color issues are there. You can check it.
> 
> Are these color issues present if you run it directly instead of building?

No

**Comment by VarunS2002** [comment]
@dipankar-npowered I'm a little busy with work, I'll get back to this soon.
