### ISSUE TITLE
Option Chain Values are not getting update 

### ISSUE THREAD

**Issue by saurabhdev9936** [VarunS2002/Python-NSE-Option-Chain-Analyzer#29]
Since Two days I am seeing below attached Results which doesn't have any data
![image](https://user-images.githubusercontent.com/55994849/143989334-4c315946-b03b-4082-8cfe-7d6e41c41d07.png)

**Comment by VarunS2002** [comment]
@saurabhdev9936 
This is actually not a problem with the app.
The NSE website is itself not working and updating any data.
Since my app retrieves data from their site, it cannot work unless their site works.
You may want to report this issue to NSE so they fix it fast

**Comment by saurabhdev9936** [comment]
okay thanks for the Quick response :)

**Comment by VarunS2002** [comment]
> okay thanks for the Quick response :)

Sure no problem.

**Comment by VarunS2002** [comment]
@saurabhdev9936 
The NSE website was working today. Closing this issue.
