### ISSUE TITLE
Save Entire Option Chain Data in Local And View in Excel Sheet.

### ISSUE THREAD

**Issue by The-Ravinder-Sharma** [VarunS2002/Python-NSE-Option-Chain-Analyzer#3]
@VarunS2002  The data of the index is refreshed by the exchange on nseindia.in after about 3 minutes and 25 seconds. This time is not fixed, there is a difference of about 20-30 seconds.

I have a request from you to please make a software from python so that whenever the data of our Banknifty's option chain is updated after 3 minutes, the exchange will be saved on our computer locally and we can see it in Excel.

It would be something like this:
The exchange will refresh its option chain after every 3 minutes and whenever it refreshes, it will also give refresh time there. Now you will check that time after every second with your software and as soon as that time is updated, you will save the entire option price in the local database giving the entire strike price and wait for the next time update and We will save it again when the data comes.

You will save these data according to the time so that according to that time in Excel, the data can be seen and your own setup can be made.

There is no email address @VarunS2002  to talk to you.
This is a very good concept.

**Comment by VarunS2002** [comment]
I didn't get exactly what you are trying to say. This program already has the option to select BANKNIFTY instead of NIFTY at the beginning and then the data can be exported to Excel on a button click. Data also refreshes every 1 minute and has the time column to see when it has refreshed.

**Comment by The-Ravinder-Sharma** [comment]
Sir, I am talking about the index trading setup of [Nitin Murarka](https://twitter.com/nitinmurarkasmc) having SMC Global.

I am saying that if we select Bank Nifty, then the software will save every minute of the data of all its strike price.
Right now our software only saves the data of the strike price that we put in the strike price. And it is just copied to Excel and does not run live.

All the strike price data of the index inside our software should be saved every minute so that we can know everything. And this software should also be live updated in Excel as well.

**Comment by The-Ravinder-Sharma** [comment]
This is something like that we scrap the data of the option chain of the entire index in Excel and we can use all kinds of strategies on it.

**Comment by The-Ravinder-Sharma** [comment]
Please View This Images.
https://pbs.twimg.com/media/EmcR5vgVgAANQ-h?format=png&name=medium
https://pbs.twimg.com/media/EnUkxRkUYAIKQij?format=jpg&name=medium
https://pbs.twimg.com/media/EnpPBjiUwAEGMO8?format=png&name=medium
https://pbs.twimg.com/media/EnqCoBmXIAENCfB?format=png&name=medium

& Also Watch This Videos
[Nitin Murarka Setup Video 1](https://www.youtube.com/watch?v=vwSjRO4wGYE)
[Nitin Murarka Setup Video 2](https://www.youtube.com/watch?v=SGhNuOLTE_M)
[Nitin Murarka Setup Video 3](https://www.youtube.com/watch?v=fjjyq4Qoztc&t=2776s)
[Nitin Murarka Setup Video 4](https://www.youtube.com/watch?v=fwRcqyoZbA0)

StoxKart Already Builded This Software With Havey Price.
[https://www.stoxkart.com/auto-trender/](https://www.stoxkart.com/auto-trender/)

**Comment by VarunS2002** [comment]
I'm currently working on a different project, I'll add this to future projects once I'm done with that.
