### ISSUE TITLE
OI Change Addition

### ISSUE THREAD

**Issue by vinayentc** [VarunS2002/Python-NSE-Option-Chain-Analyzer#30]
Hi,
Thanks a lot for the wonderful tool. Can you please add the function for "OI Change" as well along with open interest. Thanks.

**Comment by VarunS2002** [comment]
@vinayentc 
Sorry for the late reply
Is this what you are looking for?

![image](https://user-images.githubusercontent.com/30069380/148082205-d4bc405b-ccee-4db6-a50d-059a5e497f59.png)

This saves all the option chain data to a csv file so you can see whatever you want.

**Comment by vinayentc** [comment]
Hi Varun, Thanks for the response. Yes but i think it will be a enhancement to show in the tool itself the OI change difference.  
May be you can consider for any future enhancement. Therefore, closing the issue. Thanks.

**Comment by VarunS2002** [comment]
@vinayentc 
The OI values in one row listed are calculated by combining 3-4 rows from the NSE website table, so there is no corresponding OI Change value to display next to them. Thanks.
