### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by muttusarve** [VarunS2002/Python-NSE-Option-Chain-Analyzer#38]
Hi.. it is really nice work.. few suggestions :

1) is it possible to add parameters like LTP, IV.
2) charts will be more helpful, is it possible to add charts using Dash libraries, it will be easy to analyze live data on web rather than excel. because excel will crash many times.
3) if we keep live export on and when we open excel to plot the charts, the GUI is stop working and live data won't update in the exported excel.

**Comment by VarunS2002** [comment]
@muttusarve Will consider it in the future
