### ISSUE TITLE
Enhancement: Adding Multiple StrikePrices

### ISSUE THREAD

**Issue by eagles-eye-python** [VarunS2002/Python-NSE-Option-Chain-Analyzer#39]
Hi @VarunS2002 , Thank you so much creating this wonderful application, 
Is there any way we can add multiple strike prices to the list instead of only one?

**Comment by VarunS2002** [comment]
@eagles-eye-python Thanks.
But no, you can only add one strike price at a time.
You can run multiple instances at the same time with different strike prices though.

**Comment by RCNJ789** [comment]
Yes But need Software Like Autotrender.
