### ISSUE TITLE
how i can save oi and change in oi

### ISSUE THREAD

**Issue by OXENHUNTER** [VarunS2002/Python-NSE-Option-Chain-Analyzer#4]
bchaurasiya5163@mail.com

**Comment by VarunS2002** [comment]
The program currently doesn't support saving the values of  OI and Change in OI.
Is that what you wanted?

**Comment by OXENHUNTER** [comment]
can you provide your contact

**Comment by OXENHUNTER** [comment]
please you can modify this code for me

**Comment by VarunS2002** [comment]
I'm currently working on a different project, I'll add this to future projects once I'm done with that.
