### ISSUE TITLE
Failed to Fetch symbols

### ISSUE THREAD

**Issue by kpkp01** [VarunS2002/Python-NSE-Option-Chain-Analyzer#43]
Hello team,

when i run the exe file i'm getting this "failed to fetch symbols, the program will now exit." error.
[https://prnt.sc/D5qRu41MR7jU](url)
how to fix this.
thanks

**Comment by VarunS2002** [comment]
@kpkp01 
Please share some details about what values you entered, which version of the program you're running, etc and provide the logs.

**Comment by kpkp01** [comment]
@VarunS2002 

I have installed [this](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/releases/download/5.4/NSE_Option_Chain_Analyzer_5.4.exe) latest version exe file, what type of log you need, 

i didn't do anything apart from installing this package, and when i opened the app, i got this above mentioned error.

btw what type of log you need ?

**Comment by VarunS2002** [comment]
1. There will be a `NSE-OCA.ini` file in the same folder as the `.exe` file.
2. In that file set `logging = True` from `False`.
3. Open the `.exe` file and let the same error occur again.
4. There should be a new file called `NSE-OCA.log` in the same folder as the `.exe` file.
5. Upload that file here.
6. Also upload a screenshot of the error.

**Comment by VarunS2002** [comment]
@kpkp01 
Issue will be closed by this weekend due to inactivity.

**Comment by VarunS2002** [comment]
@kpkp01 Okay good.
