### ISSUE TITLE
can you please add toast notification when call sum is greater than pull sum or vice versa

### ISSUE THREAD

**Issue by saurabhdev9936** [VarunS2002/Python-NSE-Option-Chain-Analyzer#44]
Hi @VarunS2002 , Thank you so much creating this wonderful application, 
can you please add toast notification when call sum is greater than pull sum or vice versa, if you can give me the code line may be i can develop it myself , but not very good at python.

**Comment by VarunS2002** [comment]
@saurabhdev9936 

This feature already exists as shown here:

![image](https://user-images.githubusercontent.com/30069380/174640828-b4fa9b6d-fe1e-4292-b375-600aa4fbbab3.png)

The code is also already available here for the public here: 
https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/blob/master/NSE_Option_Chain_Analyzer.py

If this does not solve your query, you can reopen the issue.
