### ISSUE TITLE
Volume not available 

### ISSUE THREAD

**Issue by shivnaren** [VarunS2002/Python-NSE-Option-Chain-Analyzer#5]
Hi Varun, 

I am using this option chain Analyzer, I found that if volume available with increased or decreased number, Trade can be taken. 
Can you please try to add volume.

**Comment by VarunS2002** [comment]
You directly want the call vol and put vol values in the table ?

**Comment by VarunS2002** [comment]
Or you want the call vol sum and and put vol sum like call sum and put sum

**Comment by VarunS2002** [comment]
@shivnaren I will be closing this issue in 2 days due to inactivity

**Comment by shivnaren** [comment]
@VarunS2002 , Volume can be provided accordance to the refresh time. 

If refresh time selected
for 1 min, sum of volume for that 1 minute 
for 5 min, sum of volume for that 5 minutes 
like that can show.

**Comment by VarunS2002** [comment]
@shivnaren Call Volume Sum the same way Call Sum is calculated right?

**Comment by shivnaren** [comment]
@VarunS2002 , can you tell me one thing ? 
the Call sum is calculated for combination of 3 to 4 strick prices , right ? 
If , so, the calculation of volume calculating for 3 or 4 stricke prices i think not good for analysis. 

If possible can you get the volume from the nifty or bank nifty future. 
In future, volume is available for entire index and trade can be taken 


It is just suggestion, if you better idea , please implement it

**Comment by VarunS2002** [comment]
@shivnaren This mostly won't be added but may be possible in the future. Thanks
