### ISSUE TITLE
doesnt work coz server migrated

### ISSUE THREAD

**Issue by xbipin** [VarunS2002/Python-NSE-Option-Chain-Analyzer#54]
its seems the nse option change has been moved to a different url so it stopped working

**Comment by sant009m** [comment]
Yes for me too it has stopped working since yesterday.

**Comment by VarunS2002** [comment]
> its seems the nse option change has been moved to a different url so it stopped working

Thanks for the heads up!

**Comment by VarunS2002** [comment]
> its seems the nse option change has been moved to a different url so it stopped working

They now dynamically load the list of symbols using an API.

**Comment by xbipin** [comment]
thanks, working now with new version

**Comment by sant009m** [comment]
@VarunS2002 Thanks, its working now.
