### ISSUE TITLE
Multiple Tab in Tkinter Main Window

### ISSUE THREAD

**Issue by codewithsud** [VarunS2002/Python-NSE-Option-Chain-Analyzer#57]
Hello Varun,
Firstly, thanks for this update and development of Option Chain Analyzer. Script shows the skills you are carrying with you.

I downloaded the version 9 months back and since then modified/updated it for additional data and enhancements. i have also implemented live analysis of Index futures and Equity data and it works superbly for me. Only problem is, i need to run three different python script for these analysis.

Can you please suggest, how i can create Tab in the current GUI to add my other two analysis and present these live data in two different tab. I understand you might be busy your day to day activities, please guide me through the same.
i tried to port this GUI from TKINTER to QT5, but not successfull, yet.

I have attached the snapshot of other analysis i do for my trading. i just want to see these data in same window and different tab. These are still, work in progress.

Thanks,
Shudhanshu
![Option Chain](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/assets/121107146/84e113d3-4203-4883-bb3d-2fb6b7e2accd)
![Future Money Flow Analysis Sheet](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/assets/121107146/f5fedb6e-6298-4db6-9195-66a29d2e2abe)
![Modified Option Analyzer Sheet](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/assets/121107146/ec8bdb48-39e2-479a-ab28-02b6fd518882)
![Cash Money Flow Analysis- Top 15 Stocks](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/assets/121107146/7e35e583-5ba2-495d-b77a-2eb40ac9893b)

**Comment by VarunS2002** [comment]
@codewithsud 
It's great that you have customised the program based on your needs!
The library I use for the tables is [tksheet](https://github.com/ragardner/tksheet). I do not know whether it supports tabs like Excel supports multiple sheets. 
One solution is that you can keep retrieving and calculating all the data that you need and store it in variables and then have a menu option to switch between what you are displaying.
Did you get what I am saying?
