### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by johnbest5673** [VarunS2002/Python-NSE-Option-Chain-Analyzer#58]
Please find the error in image form, below...

![Screenshot 2023-06-16 141510](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/assets/5575342/ccbb98b8-d2d7-4009-970b-17483f65edee)

Regards...

**Comment by VarunS2002** [comment]
@johnbest5673 Is this still happening? If so, can you upload logs and describe the issue better?
