### ISSUE TITLE
Failed to fetch symbols

### ISSUE THREAD

**Issue by sant009m** [VarunS2002/Python-NSE-Option-Chain-Analyzer#62]
Hi,
  Getting error message Failed to fetch symbols

Thanks,
Santosh

![image](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/assets/5012718/55b732cf-6e79-43d8-9358-2a8bd20912be)

**Comment by VarunS2002** [comment]
@sant009m 
Is it still happening?
If so, can you please upload the logs.

**Comment by sant009m** [comment]
Its working now. Thank you
