### ISSUE TITLE
error "Failed to fetch symbols. The program will exit now exit." when click on .exe file

### ISSUE THREAD

**Issue by SagarBandkar456** [VarunS2002/Python-NSE-Option-Chain-Analyzer#65]
![image](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/assets/13567556/1ba0f39b-7da5-4eb5-b16f-6d5465dfae2f)

**Comment by shivakn2003** [comment]
This issue has cropped up again. Any resolution to this? Thanks

**Comment by VarunS2002** [comment]
Fixed in the [latest version](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/releases/5.6).

**Comment by shivakn2003** [comment]
Issue back again..in he new version.

**Comment by VarunS2002** [comment]
@shivakn2003 Are you using the python script (not the exe)?

**Comment by shivakn2003** [comment]
Yes sir, the script. (.py)
    On Wednesday 6 November, 2024 at 02:16:59 pm IST, Varun Shanbhag ***@***.***> wrote:  
 
 


@shivakn2003 Are you using the python script (not the exe)?

**Comment by VarunS2002** [comment]
@shivakn2003 Run the new `requirements.txt`

**Comment by shivakn2003** [comment]
Thanks. It works now.
    On Thursday 7 November, 2024 at 02:23:10 pm IST, Varun Shanbhag ***@***.***> wrote:  
 
 


@shivakn2003 Run the new requirements.txt
