### ISSUE TITLE
Solution for Banknifty Zero value

### ISSUE THREAD

**Issue by Sangram2905** [VarunS2002/Python-NSE-Option-Chain-Analyzer#7]
https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/blob/b72bdc94b359321dc08d342fd8a476b208597041/NSE_Option_Chain_Analyzer.py#L757

Bro, Found an solution for BankNifty Zero Value 

on line no 757 replace 

points : float = pe_values[0]['underlyingValue']

with 

points : float = ce_values[0]['underlyingValue']

Keep the great work...

**Comment by VarunS2002** [comment]
> https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/blob/b72bdc94b359321dc08d342fd8a476b208597041/NSE_Option_Chain_Analyzer.py#L757
> 
> Bro, Found an solution for BankNifty Zero Value
> 
> on line no 757 replace
> 
> points : float = pe_values[0]['underlyingValue']
> 
> with
> 
> points : float = ce_values[0]['underlyingValue']
> 
> Keep the great work...

I already fixed that issue using an alternate method here: https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/commit/72f02093609167c9f367edacc44bd7b51bf88324
This fix is also present in the latest version : 4.0
I'm closing this issue now, you can re-open this if the issue still persists.
Thanks man!
