### ISSUE TITLE
Getting jsondecodeerror >20

### ISSUE THREAD

**Issue by ravikiran032** [VarunS2002/Python-NSE-Option-Chain-Analyzer#71]
The script worked well until yesterday now it is throwing Json decode error.

**Comment by VarunS2002** [comment]
@ravikiran032 Have you updated to the latest version?

**Comment by ravikiran032** [comment]
Yes. I just downloaded and ran

**Comment by ravikiran032** [comment]
I tried nsepython library. It is also throwing same error. Is there a change in nse website data structure?

**Comment by VarunS2002** [comment]
@ravikiran032 Are you using the python script (not the exe)?

**Comment by VarunS2002** [comment]
> I tried nsepython library. It is also throwing same error. Is there a change in nse website data structure?

They changed the encoding of the api response.

**Comment by ravikiran032** [comment]
Yes I am using python script. Will exe work?

**Comment by ravikiran032** [comment]
> > I tried nsepython library. It is also throwing same error. Is there a change in nse website data structure?
> 
> They changed the encoding of the api response.

Are you going to update the code?

**Comment by VarunS2002** [comment]
> Yes I am using python script. Will exe work?

run `pip install brotli>=1.1.0`

**Comment by ravikiran032** [comment]
> > Yes I am using python script. Will exe work?
> 
> run `pip install brotli>=1.1.0`

It's working now. Thanks

**Comment by ravikiran032** [comment]
Thanks for help
