### ISSUE TITLE
error while run this code

### ISSUE THREAD

**Issue by parkashgoel** [VarunS2002/Python-NSE-Option-Chain-Analyzer#73]
![error](https://github.com/user-attachments/assets/fc78886d-108c-458d-95fd-77e636dac4c5)

**Comment by parkashgoel** [comment]
![image](https://github.com/user-attachments/assets/913e0d24-aca0-4e3c-8b8a-3389f800ee3b)

**Comment by VarunS2002** [comment]
Duplicate of #71
