### ISSUE TITLE
Enhancement : To Include Stock Options

### ISSUE THREAD

**Issue by starson007** [VarunS2002/Python-NSE-Option-Chain-Analyzer#8]
Hi Varun 

First of all, Great Job done and big thanks for sharing. 

Will it be possible for you to change the URL "https://www.nseindia.com/api/option-chain-indices" to "https://www.nseindia.com/api/quote-derivative?symbol" and provide option of "TATASTEEL". It would be great to include all stock options. I can help in creating a list in a particular format, if you need. 

I tried doing that but got following error. I am not a hardcore developer to get into it. 

Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>

**Comment by VarunS2002** [comment]
@starson007 What OS and version are you using?

**Comment by starson007** [comment]
@VarunS2002 : Windows 10 & Version is 2004.

![image](https://user-images.githubusercontent.com/77650776/105224198-e02f3b80-5b82-11eb-9d71-bb31d46b112e.png)

**Comment by VarunS2002** [comment]
@starson007 What did you do to get the PyInstaller error?

**Comment by starson007** [comment]
Hi Varun 

Thanks for prompt response. All issues have been resolved. 

The issue can be closed. 

- Bootloader issue was resolved through https://datatofish.com/executable-pyinstaller/
- The correct URL to be used is "https://www.nseindia.com/api/option-chain-equities?symbol="

**Comment by VarunS2002** [comment]
@starson007 Have you added support for stocks in this program?

**Comment by starson007** [comment]
Yes. Currently I have added only one Stock "TataSteel" i.e of my intersest. But we can add more without any much changes. 

One more change was required like many parameters for indices were being divided by 1000. But Stocks i am dividing by 10 as the number of contracts are much lower.

**Comment by VarunS2002** [comment]
Thanks!
And no I'm not trading with this program it's for my boss.
